[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "frontend/dist"
  functions = "api/functions"

# Přesměrování API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Přesměrování pro React Router SPA (zůstává)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
