[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "frontend/dist"
  functions = "api/functions"

[[redirects]]
  from = "/unminified/*"
  to = "/unminified/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/minified/*"
  to = "/minified/:splat"
  status = 200
  force = true

# React Router přesměrování pro SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
