[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "frontend/dist"
  functions = "api/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Přesměrování pro neminifikovanou verzi
[[redirects]]
  from = "/unminified/*"
  to = "/unminified/:splat"
  status = 200

# Přesměrování pro minifikovanou verzi
[[redirects]]
  from = "/minified/*"
  to = "/minified/:splat"
  status = 200

# Přesměrování pro SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
