[build]
  base = "frontend"
  publish = "frontend/dist/minified"
  command = "npm run build"
  functions = "api/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200