[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "frontend/dist"
  functions = "api/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200